### ISSUE TITLE
Missing Demo

### ISSUE THREAD

**Issue by EddLonzanida** [SpoonX/aurelia-pager#29]
Hi,

Any plans on releasing a sample/demo? 
I'm getting an error: Error: Unable to find module with ID: aurelia-pager/pager
below is my entry in main.js:
aurelia.use.plugin(PLATFORM.moduleName("aurelia-pager"));

Kindly advise. Thanks!

**Comment by VMBindraban** [comment]
You can find it here: https://github.com/SpoonX/swan-example

Can you try `aurelia.use.plugin('aurelia-pager');`?

**Comment by RWOverdijk** [comment]
@EddLonzanida Did you add it to your webpack config's resources?

**Comment by EddLonzanida** [comment]
Hi @VMBindraban the link you sent is empty.
![image](https://user-images.githubusercontent.com/25685696/28568157-5d5dd2c4-7167-11e7-8c7d-40a776a74bc5.png)

**Comment by VMBindraban** [comment]
In the docs its referring to https://swan-example.spoonx.org/

**Comment by EddLonzanida** [comment]
@RWOverdijk i'm new to webpack,, do you have an example on how to do add it as a resource?

**Comment by EddLonzanida** [comment]
Thanks @VMBindraban, i was actually hoping to see source codes here: https://github.com/SpoonX/swan-example.

**Comment by RWOverdijk** [comment]
@EddLonzanida https://github.com/SpoonX/swan-example-client

**Comment by EddLonzanida** [comment]
Well look at that! @RWOverdijk  you're a star! Thanks!
