### ISSUE TITLE
onPageChanged not working

### ISSUE THREAD

**Issue by jmdavid** [SpoonX/aurelia-pager#34]
Hi,

I have this in my html:
`<pager pages.bind="myPages" page.bind="myPage" resourceCount.bind="myResourceCount" limit.bind="limit" onPageChanged.bind="handlePageChange"></pager>`

and this in my js:

`handlePageChange(oldValue, newValue) {
  	console.log("new value: " + newValue);
  }`

But my function is never called. :(

**Comment by jmdavid** [comment]
I realized that I should use call instead of bind but it doesn't work eather:

`onPageChanged.call="handlePageChage($newValue, $oldValue)"`

**Comment by VMBindraban** [comment]
Can you try `delegate()` instead of `call()`?

**Comment by jmdavid** [comment]
same result with delegate.

**Comment by VMBindraban** [comment]
Ah, it's a binding issue.

Try `on-page-changed.bind=""`.
`resourceCount` properly has the same issue.

When a bindable is camel-cased you need to write it with dashes in html.

**Comment by jmdavid** [comment]
Yeah!
`on-page-changed.bind="handlePageChange`
did the job!

Thanks.

Documentation should be updated with that.

**Comment by RWOverdijk** [comment]
@jmdavid Feel free to submit a PR! :)
