### ISSUE TITLE
how to use onPageChanged event in pager tag

### ISSUE THREAD

**Issue by meta-pratap-ranawat** [SpoonX/aurelia-pager#35]
Hi there,
I am not able to use onPageChanged property of pager.

i tried
html
```
 <pager pages.bind="pages" page.bind="page"  onPageChanged.bind="HandlePageChanged"></pager>
<pager pages.bind="pages" page.bind="page"  onPageChanged.bind="HandlePageChanged(newValue, oldValue)">
</pager>
<pager pages.bind="pages" page.bind="page"  onPageChanged.bind="HandlePageChanged()">
</pager>
 <pager pages.bind="pages" page.bind="page"  onPageChanged.delegate="HandlePageChanged"></pager>
<pager pages.bind="pages" page.bind="page"  onPageChanged.delegate="HandlePageChanged(newValue, oldValue)">
</pager>
<pager pages.bind="pages" page.bind="page"  onPageChanged.delegate="HandlePageChanged()">
</pager>
```

in ts(javascript)

```
HandlePageChanged(newValue, oldValue)
{
//do your work
}
```

nothing is working for me

can anyone help me with demo example.

Thanks in Advance

**Comment by doktordirk** [comment]
as per aurelia convention, all those öhm bindable properties are converted by aurelia itself from camelCase to camel-case in the view. ( i think there was browser who can't handle camelCase in markup. or is that valid for all browser? well, anyways..) 
hence try `on-page-changed.bind="HandlePageChanged"` and alike

in view.js
HandlePageChanged(page){console.log(page)} gives the page with above binding

**Comment by meta-pratap-ranawat** [comment]
thanks, problem is now solved at my end @doktordirk

**Comment by mttmccb** [comment]
I know this has been solved but I prefer 

`on-page-changed.call="HandlePageChanged(newValue, oldValue)` so it's in the context of the parent not the pager.
